#!/bin/bash

_term() {
  echo "Caught SIGTERM signal!"
  # kill -TERM "$PID" 2>/dev/null
  exit 0
}

trap _term SIGTERM

echo 'command:' "$@"

# a script in the binder sub-directory take precedence
if [ -f ./binder/start ]; then
  chmod u+x ./binder/start
  nix-shell default.nix --command "./binder/start $@" &
elif [ -f ./start ]; then
  chmod u+x ./start
  nix-shell default.nix --command "./start $@" &
else
  nix-shell default.nix --command "$@" &
fi

PID=$!
echo 'waiting'

wait "$PID"
