#!/usr/bin/env python
import sys

assert sys.version_info[:2] == (3, 10), sys.version

import numpy

try:
    import there
except ImportError:
    pass
else:
    raise Exception("'there' shouldn't have been installed from requirements.txt")
