#!/usr/bin/env python
import sys
import os

# Python should still be in /srv/conda
assert sys.executable == os.path.join(os.environ['NB_PYTHON_PREFIX'], 'bin', 'python')

# Repo should be in /srv/repo
assert os.path.exists('/srv/repo/verify')
assert os.path.abspath(__file__) == '/srv/repo/verify'

# We should be able to import the package in environment.yml
import numpy
