# dependabot.yaml reference: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
#
# Notes:
# - Status and logs from dependabot are provided at
#   https://github.com/jupyterhub/repo2docker/network/updates.
# - YAML anchors are not supported here or in GitHub Workflows.
#
version: 2
updates:
  # Maintain dependencies in our GitHub Workflows
  - package-ecosystem: github-actions
    directory: /
    labels: [ci]
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - "*"

  # Update frozen requirements in repo2docker Dockerfile
  - package-ecosystem: pip
    directory: /
    allow:
      # need this to upgrade requirements.txt
      # otherwise only direct dependencies in requirements.in will be updated
      - dependency-type: all
    labels: [dependencies]
    groups:
      dockerfile:
        patterns:
          - "*"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
