tasks:
  - init: |
      pip3 install sphinx-autobuild
      pip3 install -r dev-requirements.txt
      pip3 install -r docs/requirements.txt
      pip3 install -e .
    command: |
      sphinx-autobuild docs/source/ docs/_build/html/
    name: Sphinx preview
      
ports:
  - port: 8000
