#!/usr/bin/env Rscript
library('ggplot2')

print(version)
# Fail if version is not 4.0
if (!(version$major == "4" && as.double(version$minor) >= 0 && as.double(version$minor) < 1)) {
  quit("yes", 1)
}
