#!/usr/bin/env Rscript
library('ggplot2')

print(version)
# Fail if version is not 4.0
if (!(version$major == "4" && as.double(version$minor) >= 0 && as.double(version$minor) < 1)) {
  quit("yes", 1)
}

# The date we have chosen should give us an MRAN mirror
if (!grepl("https://mran.microsoft.com", options()$CRAN, fixed=TRUE)) {
  quit("yes", 1)
}
