#!/usr/bin/env julia
# We try to plot something, and see if the file saved exists
using PyPlot
x = linspace(0,2*pi,1000); y = sin(3*x + 4*cos(2*x))
plot(x, y, color="red", linewidth=2.0, linestyle="--")
savefig("graph.png")
if isfile("graph.png")
    exit(0)
else
    exit(1)
end

