#!/usr/bin/env julia
using PyPlot

# Make sure we are re-using the same conda python
if ! startswith(PyCall.libpython, ENV["NB_PYTHON_PREFIX"] * "/lib")
    println("Not re-using conda python! Using " * PyCall.libpython * " instead")
    exit(1)
end

# We try to plot something, and see if the file saved exists
x = linspace(0,2*pi,1000); y = sin(3*x + 4*cos(2*x))
plot(x, y, color="red", linewidth=2.0, linestyle="--")
savefig("graph.png")
if isfile("graph.png")
    exit(0)
else
    exit(1)
end
