#!/usr/bin/env julia

if VERSION != v"1.8.2"
    println("Julia version should be 1.8.2")
    exit(1)
end

# Verify that the environment variables are set correctly for julia 1.0+
@assert "julia" ∈ readdir(Sys.BINDIR)

try
    # Test that the package was installed.
    using Adapt
catch
    println("Should be able to load Adapt")
    exit(1)
end

try
    using IteratorInterfaceExtensions
    # Test that the package was not installed.
    println("Should not be able to load IteratorInterfaceExtensions")
    exit(1)
catch
end

exit(0)
