#!/usr/bin/env julia

if VERSION != v"1.3"
    println("Julia version should be 1.3, got $VERSION")
    exit(1)
end

try
    # Test that the package was installed.
    using IteratorInterfaceExtensions

    # Verify that the environment variables are set correctly for julia 1.0+
    @assert "julia" ∈ readdir(Sys.BINDIR)
catch
    exit(1)
end

# Verify that kernels are not installed in home directory (issue #620)
try
    using IJulia
    @assert IJulia.kerneldir() == ENV["NB_PYTHON_PREFIX"] * "/share/jupyter/kernels"
catch
    exit(1)
end

exit(0)
