#!/usr/bin/env julia

if VERSION != v"0.6.4"
    println("Julia version was: ", VERSION)
    println("Default Julia version expected to be 0.6.4 when unspecified in a REQUIRE file")
    exit(1)
end

try
    # Test that the package was installed.
    using Compat

    # Verify that the environment variables are set correctly for julia < 0.7
    @assert "julia" ∈ readdir(Base.JULIA_HOME)
catch
    exit(1)
end

exit(0)
