#!/usr/bin/env python

try:
    import sampleproject
except ImportError:
    # We want an ImportError to be thrown for this test to pass
    pass
else:
    raise Exception(
        "'sampleproject' shouldn't have been installed! It was listed in Pipfile but not in the Pipfile.lock."
    )
