#!/usr/bin/env Rscript
library('testthat')

print(version)
# Fail if version is not 4.0
if (!(version$major == "4" && as.double(version$minor) >= 0 && as.double(version$minor) < 1)) {
  quit("yes", 1)
}

# The date we have chosen should give us an rspm mirror
if (!(startsWith(options()$repos["CRAN"], "https://packagemanager.rstudio.com"))) {
  quit("yes", 1)
}