#!/usr/bin/env Rscript
library('digest')

# Fail if version is not 4.5
print(version)
if (!(version$major == "4" && as.double(version$minor) >= 5 && as.double(version$minor) < 6)) {
  quit("yes", 1)
}

# The date we have chosen should give us an rspm mirror
if (!(startsWith(options()$repos["CRAN"], "https://packagemanager.posit.co"))) {
  quit("yes", 1)
}
