#!/usr/bin/env julia
# Verify the version:
if VERSION != v"0.6.3"
    exit(1)
end

try
    # Test that the package was installed.
    using Compat

    # Verify that the environment variables are set correctly for julia <= 0.6
    @assert "julia" ∈ readdir(Base.JULIA_HOME)
catch
    exit(1)
end

# Verify that kernels are not installed in home directory (issue #620)
try
    using IJulia
    @assert IJulia.kerneldir() == "/srv/conda/share/jupyter/kernels"
catch
    exit(1)
end

exit(0)
