from .base import Local
from .ckan import CKAN
from .dataverse import Dataverse
from .figshare import Figshare
from .git import Git
from .hydroshare import Hydroshare
from .mercurial import Mercurial
from .swhid import Swhid
from .zenodo import Zenodo
