#!/usr/bin/env Rscript
library('testthat')

# Fail if version is not 4.1
if (!(version$major == "4" && as.double(version$minor) >= 1 && as.double(version$minor) < 2)) {
  quit("yes", 1)
}

# R 4.1 always uses rspm snapshots
if (!(startsWith(options()$repos["CRAN"], "https://packagemanager.rstudio.com"))) {
  quit("yes", 1)
}
