#!/usr/bin/env Rscript
library('tinytest')

print(version)

# Fail if MRAN isn't the configured CRAN mirror
if (!(startsWith(options()$repos["CRAN"], "https://mran.microsoft.com"))) {
  quit("yes", 1)
}
