#!/usr/bin/env python
import sys
from subprocess import check_output

assert sys.version_info[:2] == (3, 5), sys.version

out = check_output(["/tmp/bin/micromamba", "--version"]).decode("utf8").strip()
assert out == "0.12.2", out

import numpy
