#!/usr/bin/env python
import sys
from subprocess import check_output

assert sys.version_info[:2] == (3, 5), sys.version

out = check_output(["micromamba", "--version"]).decode("utf8").strip()
assert (
    out
    == """micromamba: 0.19.1
libmamba: 0.19.1"""
), out

out = check_output(["mamba", "--version"]).decode("utf8").strip()
assert (
    out
    == """mamba 0.19.1
conda 4.11.0"""
), out

import numpy
